name: Auto Push

on:
  schedule:
    - cron: '21 14 * * *'  # Runs at midnight UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          git add output/*
          git add index.html
          git commit -m "Automated commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
