name: Auto Push

on:
  schedule:
    - cron: '53 14 * * *'  # Runs at 14:15 UTC (16:15 CEST) every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Add commands to make changes here
        # Example: echo "Hello World" > output/hello.txt
        echo "Hello World" > output/hello.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/ index.html
        git commit -m "Automated changes to output directory and index.html" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
